"""
Purpose: Lifecycle config generator — turn a scan run's stale rollups plus
the band→target map into COMPLETE per-bucket S3 lifecycle configurations,
validated hard before anything is written. PUT replaces a bucket's entire
config, so a generated file is always the full rule set, never a delta.
Author(s): John Reed
"""

import re

from tagmanager.storage.projections import (INT_ALLOWED_TARGETS,
                                            TRANSITION_SOURCE_CLASSES,
                                            default_band_targets)
from tagmanager.storage.rollup import SMALL_OBJECT_FLOOR_BYTES, band_labels

# Constants

IA_CLASSES = ("STANDARD_IA", "ONEZONE_IA")
GLACIER_CLASSES = ("GLACIER_IR", "GLACIER", "DEEP_ARCHIVE")
MIN_IA_DAYS = 30
MIN_CHAIN_GAP_DAYS = 30
MAX_RULES = 1000
MAX_ID_LEN = 255

APPLY_HEADER = ("Generated by TagManager — applying REPLACES the bucket's "
                "ENTIRE lifecycle configuration; merge by hand if the bucket "
                "already has rules.")


class LifecycleValidationError(ValueError):
    """Raised when a generated config would violate S3 lifecycle rules."""


def _rule_id(prefix, suffix):
    """Build a readable, S3-legal rule ID from a prefix."""
    slug = re.sub(r"[^A-Za-z0-9._-]+", "-", prefix or "root").strip("-")
    return f"tagmanager-{slug}-{suffix}"[:MAX_ID_LEN]


def _stale_prefixes(stats, age_band_days):
    """
    Bucket -> {prefix -> set of source classes with stale cells}.

    :param stats: StoragePrefixStat rows
    :param age_band_days: run thresholds
    :returns: nested dict
    """
    fresh_label = band_labels(age_band_days)[0]
    out = {}
    for stat in stats:
        if stat.age_band == fresh_label:
            continue
        out.setdefault(stat.container, {}).setdefault(
            stat.prefix, set()).add(stat.storage_class)
    return out


def _transitions_for(age_band_days, targets):
    """
    The full transition ladder implied by the band→target map.

    :param age_band_days: run thresholds
    :param targets: band label -> storage class
    :returns: sorted list of {"Days": int, "StorageClass": str}
    """
    labels = band_labels(age_band_days)
    transitions = []
    for i, day in enumerate(age_band_days):
        target = targets.get(labels[i + 1])
        if target:
            transitions.append({"Days": day, "StorageClass": target})
    # Collapse repeated targets — keep the earliest Days for each class.
    seen = {}
    for tran in transitions:
        if tran["StorageClass"] not in seen:
            seen[tran["StorageClass"]] = tran
    return sorted(seen.values(), key=lambda tran: tran["Days"])


def build_lifecycle_configs(stats, age_band_days, band_targets=None,
                            delete_after=None):
    """
    Generate one complete lifecycle config per bucket with stale data.

    Prefixes whose stale cells are ALL Intelligent-Tiering get no rule when
    the mapped target is not a legal INT destination — collected in the
    returned skips instead of silently emitting a rule that cannot fire.

    :param stats: StoragePrefixStat rows (one run)
    :param age_band_days: run thresholds
    :param band_targets: optional day-keyed target overrides
    :param delete_after: optional Expiration days (delete flavor)
    :returns: (configs: {bucket: config_dict}, skips: [reason strings])
    """
    targets = default_band_targets(age_band_days, overrides=band_targets)
    transitions = _transitions_for(age_band_days, targets)
    configs = {}
    skips = []

    for bucket, prefixes in _stale_prefixes(stats, age_band_days).items():
        rules = _bucket_rules(bucket, prefixes, transitions, delete_after,
                              skips)
        if rules:
            configs[bucket] = {"Rules": rules}

    for config in configs.values():
        validate_config(config)
    return configs, skips


def _bucket_rules(bucket, prefixes, transitions, delete_after, skips):
    """
    Rules for one bucket's stale prefixes; skip reasons appended to skips.

    :param bucket: bucket name (for skip messages)
    :param prefixes: {prefix -> set of storage classes}
    :param transitions: the run's transition ladder
    :param delete_after: optional Expiration days
    :param skips: skip-reason list (mutated)
    :returns: list of rule dicts
    """
    rules = []
    for prefix, classes in sorted(prefixes.items()):
        rule, reason = _rule_for_prefix(prefix, classes, transitions,
                                        delete_after)
        if rule is None:
            skips.append(f"{bucket}/{prefix}: {reason}")
        else:
            rules.append(rule)
    return rules


def _rule_for_prefix(prefix, classes, transitions, delete_after):
    """
    One lifecycle rule for a stale prefix, or (None, reason) when skipped.

    :param prefix: rollup prefix
    :param classes: storage classes seen stale under the prefix
    :param transitions: the run's transition ladder
    :param delete_after: optional Expiration days
    :returns: (rule dict, None) or (None, skip reason)
    """
    eligible = classes & set(TRANSITION_SOURCE_CLASSES)
    if not eligible:
        return None, "no transition-eligible storage classes"
    if eligible == {"INTELLIGENT_TIERING"}:
        bad = [tran["StorageClass"] for tran in transitions
               if tran["StorageClass"] not in INT_ALLOWED_TARGETS]
        if bad:
            return None, ("all objects in INTELLIGENT_TIERING and "
                          f"{'/'.join(bad)} is not a legal INT destination")
    rule = {
        "ID": _rule_id(prefix, "age-out"),
        "Status": "Enabled",
        "Filter": {"And": {
            "Prefix": f"{prefix}/" if prefix else "",
            "ObjectSizeGreaterThan": SMALL_OBJECT_FLOOR_BYTES,
        }},
        "Transitions": [dict(tran) for tran in transitions],
    }
    if delete_after is not None:
        rule["Expiration"] = {"Days": delete_after}
    return rule, None


def validate_config(config):
    """
    Enforce S3 lifecycle constraints on a generated config. Raises —
    an invalid artifact is a generation error, never a warning in a
    broken file.

    :param config: {"Rules": [...]}
    :raises LifecycleValidationError: any violated constraint
    """
    rules = config.get("Rules", [])
    if not rules:
        raise LifecycleValidationError("config has no rules")
    if len(rules) > MAX_RULES:
        raise LifecycleValidationError(
            f"{len(rules)} rules exceeds the S3 limit of {MAX_RULES}")

    for rule in rules:
        rid = rule.get("ID", "?")
        if len(rid) > MAX_ID_LEN:
            raise LifecycleValidationError(f"rule ID too long: {rid[:40]}...")
        and_filter = rule.get("Filter", {}).get("And", {})
        if "ObjectSizeGreaterThan" not in and_filter:
            raise LifecycleValidationError(
                f"{rid}: ObjectSizeGreaterThan must be explicit — AWS "
                "excludes <128 KiB objects from transitions by default")

        transitions = sorted(rule.get("Transitions", []),
                             key=lambda tran: tran["Days"])
        ia_days = None
        for tran in transitions:
            sclass, days = tran["StorageClass"], tran["Days"]
            if sclass in IA_CLASSES:
                if days < MIN_IA_DAYS:
                    raise LifecycleValidationError(
                        f"{rid}: {sclass} transition at {days}d is below "
                        f"the {MIN_IA_DAYS}d minimum")
                ia_days = days
            if (sclass in GLACIER_CLASSES and ia_days is not None
                    and days - ia_days < MIN_CHAIN_GAP_DAYS):
                raise LifecycleValidationError(
                    f"{rid}: {sclass} at {days}d is under "
                    f"{MIN_CHAIN_GAP_DAYS}d after the IA transition at "
                    f"{ia_days}d")

        expiration = rule.get("Expiration")
        if expiration is not None:
            max_transition = max((tran["Days"] for tran in transitions),
                                 default=0)
            if expiration["Days"] <= max_transition:
                raise LifecycleValidationError(
                    f"{rid}: Expiration at {expiration['Days']}d must exceed "
                    f"the last transition at {max_transition}d")
